"use client"
import Link from "next/link"
import { useState } from "react"
import { AlertTriangle,ArrowLeft,Check,ShieldCheck,X } from "lucide-react"
import { decisions } from "@/lib/mock-api"
import { approveAiDecision,rejectAiDecision } from "@/lib/api"
import { humanizeApiError } from "@/lib/api/errors"

export function DecisionAudit({id}:{id:string}){const decision=decisions.find(item=>item.id===id)??decisions[0];const [busy,setBusy]=useState(false);const [result,setResult]=useState("");async function act(kind:"approve"|"reject"){setBusy(true);setResult("");try{if(kind==="approve"){const order=await approveAiDecision(decision.id);setResult(`Ordre ${order.id} créé avec le statut ${order.status}.`)}else{await rejectAiDecision(decision.id);setResult("Proposition rejetée. La décision reste dans le journal d’audit.")}}catch(error){setResult(humanizeApiError(error instanceof Error?{error:"UNKNOWN",message:error.message}:"UNKNOWN").message)}finally{setBusy(false)}}return <main className="audit-page"><Link className="back" href="/agent"><ArrowLeft/> Retour au journal</Link><header className="audit-header"><div><span className="eyebrow">{decision.modelUsed} • THINKING {decision.thinkingLevel.toUpperCase()}</span><h1>{decision.action} {decision.symbol}</h1><p>{decision.reasoningSummary}</p></div><span className={`pill ${decision.validationPassed?"good":"bad"}`}>{decision.validationPassed?<ShieldCheck/>:<AlertTriangle/>}{decision.validationPassed?"VALIDÉ PAR LES RÈGLES":"BLOQUÉ"}</span></header><section className="audit-layout"><article className="panel reasoning"><div className="panel-head"><div><span className="eyebrow">TRACE EXPLICABLE</span><h2>Raisonnement intégral</h2></div><span className="mono">{Math.round(decision.confidenceScore*100)} % confiance</span></div><p>{decision.fullReasoning}</p><h3>Facteurs déterminants</h3><ul>{decision.keyFactors.map(factor=><li key={factor}>{factor}</li>)}</ul></article><aside className="panel audit-side"><span className="eyebrow">PROPOSITION</span><dl><div><dt>Action</dt><dd>{decision.action}</dd></div><div><dt>Quantité</dt><dd className="mono">{decision.proposedQuantity??"—"}</dd></div><div><dt>Stop loss</dt><dd className="mono">{decision.proposedStopLoss??"—"}</dd></div><div><dt>Take profit</dt><dd className="mono">{decision.proposedTakeProfit??"—"}</dd></div></dl>{decision.validationErrors.length>0&&<div className="validation-list"><strong>Règles non satisfaites</strong>{decision.validationErrors.map(error=><span key={error}><X/>{error}</span>)}</div>}<div className="audit-actions"><button className="primary" disabled={busy||!decision.validationPassed||decision.action==="HOLD"} onClick={()=>act("approve")}><Check/> Approuver</button><button className="ghost danger" disabled={busy} onClick={()=>act("reject")}><X/> Rejeter</button></div>{result&&<p className="action-result" role="status">{result}</p>}<small>La réponse brute du modèle n’est accessible que via la route d’audit technique protégée. Elle n’est jamais rendue ici.</small></aside></section></main>}
