"use client"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useMemo,useState } from "react"
import { ArrowRight,Eye,EyeOff,ShieldCheck } from "lucide-react"
import { AuthError,authMessage,signIn,signInWithGoogle,signUp } from "@/lib/auth/client"

type Mode="login"|"signup"
export function AuthScreen({mode}:{mode:Mode}){const router=useRouter();const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const emailValid=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);const strength=useMemo(()=>[password.length>=8,/\d/.test(password),/[A-Z]/.test(password)].filter(Boolean).length,[password]);const valid=emailValid&&password.length>=8&&(mode==="login"||name.trim().length>=2)
async function submit(event:React.FormEvent){event.preventDefault();if(!valid||busy)return;setBusy(true);setError("");try{if(mode==="login")await signIn(email,password);else await signUp(email,password,name);router.push(mode==="signup"?"/welcome":"/")}catch(value){setError(value instanceof AuthError?authMessage(value.code):"Connexion impossible. Réessayez.")}finally{setBusy(false)}}
async function google(){setBusy(true);setError("");try{await signInWithGoogle();router.push(mode==="signup"?"/welcome":"/")}catch{setError("Connexion Google indisponible.")}finally{setBusy(false)}}
return <main className="auth-page"><section className="auth-principle"><Link href="/" className="brand auth-brand"><span className="brand-mark">L</span><span><strong>LEDGER</strong><small>SIMULATED MARKETS</small></span></Link><div><span className="eyebrow">DISCIPLINE FINANCIÈRE</span><h1>L&apos;argent est fictif.<br/>Vos décisions ne le sont pas.</h1><p>Un environnement de simulation qui traite chaque ordre, chaque perte et chaque limite comme dans un compte réel.</p></div><div className="auth-proof"><ShieldCheck/><span><strong>10 000 $</strong> de capital initial</span><span>Slippage et rejets simulés</span><span>Historique d&apos;audit complet</span></div></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit} noValidate><div><span className="eyebrow">{mode==="login"?"BON RETOUR":"OUVRIR UN COMPTE"}</span><h2>{mode==="login"?"Se connecter":"Commencer avec 10 000 $ fictifs"}</h2><p>{mode==="login"?"Retrouvez votre journal et vos limites.":"Le capital initial n’est pas remis à zéro facilement."}</p></div>{mode==="signup"&&<label>NOM AFFICHÉ<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} aria-invalid={name.length>0&&name.trim().length<2}/>{name.length>0&&name.trim().length<2&&<small className="field-error">Saisissez au moins 2 caractères.</small>}</label>}<label>ADRESSE E-MAIL<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} aria-invalid={email.length>0&&!emailValid}/>{email.length>0&&!emailValid&&<small className="field-error">Format d&apos;e-mail invalide.</small>}</label><label>MOT DE PASSE<span className="password-input"><input type={show?"text":"password"} autoComplete={mode==="login"?"current-password":"new-password"} value={password} onChange={e=>setPassword(e.target.value)} aria-invalid={password.length>0&&password.length<8}/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?"Masquer le mot de passe":"Afficher le mot de passe"}>{show?<EyeOff/>:<Eye/>}</button></span>{mode==="signup"&&<span className="strength" aria-label={`Force du mot de passe ${strength} sur 3`}><i className={strength>0?"on":""}/><i className={strength>1?"on":""}/><i className={strength>2?"on":""}/><small>8 caractères, un chiffre, une majuscule</small></span>}</label>{error&&<div className="form-error" role="alert">{error}</div>}<button className="primary full" disabled={!valid||busy}>{busy?"Vérification…":mode==="login"?"Se connecter":"Créer mon compte"}<ArrowRight data-icon="inline-end"/></button><div className="auth-divider"><span>OU</span></div><button type="button" className="google" disabled={busy} onClick={google}><span>G</span> Continuer avec Google</button><p className="auth-switch">{mode==="login"?"Pas encore de compte ?":"Déjà un compte ?"} <Link href={mode==="login"?"/signup":"/login"}>{mode==="login"?"Créer un compte":"Se connecter"}</Link></p></form></section></main>}
