import { z } from "zod"

export const userSchema=z.object({id:z.string(),email:z.email(),displayName:z.string(),createdAt:z.iso.datetime()})
export const accountSchema=z.object({id:z.string(),userId:z.string(),balance:z.number(),startingBalance:z.number(),createdAt:z.iso.datetime()})
export const accountSummarySchema=z.object({balance:z.number(),totalPositionsValue:z.number(),totalPnl:z.number(),totalPnlPercent:z.number()})
export const assetSchema=z.object({symbol:z.string(),name:z.string(),type:z.enum(["stock","crypto"]),exchange:z.string()})
export const priceTickSchema=z.object({symbol:z.string(),price:z.number(),timestamp:z.iso.datetime(),change24h:z.number()})
export const positionSchema=z.object({id:z.string(),accountId:z.string(),symbol:z.string(),quantity:z.number(),avgEntryPrice:z.number(),currentPrice:z.number(),unrealizedPnl:z.number(),unrealizedPnlPercent:z.number(),stopLoss:z.number().nullable(),takeProfit:z.number().nullable(),leverage:z.number(),openedAt:z.iso.datetime()})
export const orderSchema=z.object({id:z.string(),accountId:z.string(),symbol:z.string(),type:z.enum(["market","limit"]),side:z.enum(["buy","sell"]),quantity:z.number(),limitPrice:z.number().nullable(),requestedPrice:z.number(),filledPrice:z.number().nullable(),slippage:z.number().nullable(),status:z.enum(["pending","filled","rejected","cancelled"]),source:z.enum(["manual","ai_agent"]),stopLoss:z.number().nullable(),takeProfit:z.number().nullable(),rejectionReason:z.string().nullable(),createdAt:z.iso.datetime(),filledAt:z.iso.datetime().nullable()})
export const aiDecisionSchema=z.object({id:z.string(),accountId:z.string(),symbol:z.string(),action:z.enum(["BUY","SELL","HOLD"]),confidenceScore:z.number().min(0).max(1),proposedQuantity:z.number().nullable(),proposedStopLoss:z.number().nullable(),proposedTakeProfit:z.number().nullable(),fullReasoning:z.string(),reasoningSummary:z.string(),keyFactors:z.array(z.string()),validationPassed:z.boolean(),validationErrors:z.array(z.string()),resultingOrderId:z.string().nullable(),modelUsed:z.enum(["gemini-3.7-flash","gemini-3.6-flash"]),thinkingLevel:z.enum(["low","medium","high"]),createdAt:z.iso.datetime()})
export const aiConfigSchema=z.object({accountId:z.string(),enabled:z.boolean(),mode:z.enum(["propose","autonomous"]),watchedSymbols:z.array(z.string()),maxPositionSizePercent:z.number(),dailyLossLimitPercent:z.number(),circuitBreakerActive:z.boolean(),circuitBreakerReason:z.string().nullable()})
export const createOrderSchema=z.object({symbol:z.string().min(1),type:z.enum(["market","limit"]),side:z.enum(["buy","sell"]),quantity:z.number().positive(),limitPrice:z.number().positive().nullable().optional(),stopLoss:z.number().positive().nullable().optional(),takeProfit:z.number().positive().nullable().optional()}).superRefine((v,ctx)=>{if(v.type==="limit"&&!v.limitPrice)ctx.addIssue({code:"custom",path:["limitPrice"],message:"Le prix limite est requis."})})
