import { assetSchema, decisionSchema, orderSchema, positionSchema, type AiDecision, type Order } from "./trading"
const delay=()=>new Promise(r=>setTimeout(r,120+Math.random()*280))
export const assets=assetSchema.array().parse([
{symbol:"AAPL",name:"Apple Inc.",type:"stock",exchange:"NASDAQ"},{symbol:"NVDA",name:"NVIDIA",type:"stock",exchange:"NASDAQ"},{symbol:"MSFT",name:"Microsoft",type:"stock",exchange:"NASDAQ"},{symbol:"TSLA",name:"Tesla",type:"stock",exchange:"NASDAQ"},{symbol:"BTCUSDT",name:"Bitcoin",type:"crypto",exchange:"BINANCE"},{symbol:"ETHUSDT",name:"Ethereum",type:"crypto",exchange:"BINANCE"}])
export const prices:Record<string,{price:number;change:number}>={AAPL:{price:226.34,change:1.42},NVDA:{price:181.62,change:-0.86},MSFT:{price:521.14,change:.38},TSLA:{price:337.92,change:-2.17},BTCUSDT:{price:116842.15,change:2.76},ETHUSDT:{price:4521.42,change:1.19}}
export const positions=positionSchema.array().parse([
{id:"p1",accountId:"acc_01",symbol:"AAPL",quantity:8,avgEntryPrice:218.4,currentPrice:226.34,unrealizedPnl:63.52,unrealizedPnlPercent:3.64,stopLoss:209,takeProfit:242,leverage:1,openedAt:"2026-08-12T14:20:00Z"},{id:"p2",accountId:"acc_01",symbol:"BTCUSDT",quantity:.018,avgEntryPrice:112400,currentPrice:116842.15,unrealizedPnl:79.96,unrealizedPnlPercent:3.95,stopLoss:108000,takeProfit:124000,leverage:1,openedAt:"2026-08-18T09:12:00Z"},{id:"p3",accountId:"acc_01",symbol:"NVDA",quantity:6,avgEntryPrice:185.8,currentPrice:181.62,unrealizedPnl:-25.08,unrealizedPnlPercent:-2.25,stopLoss:176,takeProfit:205,leverage:1,openedAt:"2026-08-20T16:08:00Z"}])
export let orders:Order[]=orderSchema.array().parse([
{id:"ord_1042",accountId:"acc_01",symbol:"BTCUSDT",type:"market",side:"buy",quantity:.018,limitPrice:null,requestedPrice:112310,filledPrice:112400,slippage:.08,status:"filled",source:"manual",stopLoss:108000,takeProfit:124000,rejectionReason:null,createdAt:"2026-08-18T09:12:00Z",filledAt:"2026-08-18T09:12:02Z"},{id:"ord_1038",accountId:"acc_01",symbol:"TSLA",type:"limit",side:"buy",quantity:12,limitPrice:320,requestedPrice:329.4,filledPrice:null,slippage:null,status:"cancelled",source:"manual",stopLoss:null,takeProfit:null,rejectionReason:null,createdAt:"2026-08-15T15:31:00Z",filledAt:null},{id:"ord_1029",accountId:"acc_01",symbol:"NVDA",type:"market",side:"buy",quantity:6,limitPrice:null,requestedPrice:185.65,filledPrice:185.8,slippage:.081,status:"filled",source:"ai_agent",stopLoss:176,takeProfit:205,rejectionReason:null,createdAt:"2026-08-20T16:08:00Z",filledAt:"2026-08-20T16:08:03Z"}])
export const decisions:AiDecision[]=decisionSchema.array().parse([
{id:"ai_88",accountId:"acc_01",symbol:"MSFT",action:"HOLD",confidenceScore:.74,proposedQuantity:null,proposedStopLoss:null,proposedTakeProfit:null,fullReasoning:"La tendance primaire reste constructive, mais le prix évolue actuellement près d’une zone de résistance identifiée sur les trois dernières séances. Le volume acheteur ralentit tandis que la volatilité implicite demeure élevée.\n\nUne entrée immédiate offrirait un ratio rendement/risque insuffisant au regard de la limite de position configurée. Attendre une consolidation ou une confirmation au-dessus de 524 USD réduit le risque d’acheter une extension de court terme.\n\nLa décision HOLD ne signifie pas une absence de scénario. Le symbole reste surveillé et sera réévalué au prochain cycle avec une attention particulière portée au volume relatif et à la tenue du support à 515 USD.",reasoningSummary:"Résistance proche et volume en baisse : attendre une confirmation avant toute exposition.",keyFactors:["Résistance à 524 $","Volume relatif 0,82×","Volatilité élevée"],validationPassed:true,validationErrors:[],resultingOrderId:null,modelUsed:"gemini-3.7-flash",thinkingLevel:"high",createdAt:"2026-08-22T14:18:00Z"},{id:"ai_87",accountId:"acc_01",symbol:"NVDA",action:"BUY",confidenceScore:.68,proposedQuantity:6,proposedStopLoss:176,proposedTakeProfit:205,fullReasoning:"Le repli ramène le titre sur une zone de support court terme, avec un RSI revenu en territoire neutre. Le scénario propose une taille volontairement limitée.\n\nLa validation de risque passe : l’exposition reste sous la limite configurée et le stop se situe à moins de 10 % du prix spot. L’asymétrie reste acceptable, sans considérer ce signal comme certain.",reasoningSummary:"Repli sur support avec exposition limitée et stop conforme aux règles.",keyFactors:["Support technique","RSI normalisé","Taille limitée"],validationPassed:true,validationErrors:[],resultingOrderId:"ord_1029",modelUsed:"gemini-3.7-flash",thinkingLevel:"medium",createdAt:"2026-08-20T16:07:00Z"},{id:"ai_86",accountId:"acc_01",symbol:"BTCUSDT",action:"BUY",confidenceScore:.81,proposedQuantity:.12,proposedStopLoss:101000,proposedTakeProfit:128000,fullReasoning:"Le momentum est positif mais la taille demandée dépasse l’enveloppe de risque autorisée. Le signal ne doit pas être exécuté malgré une confiance directionnelle élevée.",reasoningSummary:"Signal directionnel positif, rejeté car la taille excède la limite de risque.",keyFactors:["Momentum positif","Taille excessive"],validationPassed:false,validationErrors:["POSITION_SIZE_EXCEEDED"],resultingOrderId:null,modelUsed:"gemini-3.6-flash",thinkingLevel:"medium",createdAt:"2026-08-19T10:42:00Z"}])
export async function loadAll(){await delay();return {assets,positions,orders,decisions}}
export async function createOrder(input:{symbol:string;side:"buy"|"sell";type:"market"|"limit";quantity:number;limitPrice:number|null;stopLoss:number|null;takeProfit:number|null}){await delay();const p=prices[input.symbol]?.price??0;const slip=input.type==="market"?.0008:0;const order=orderSchema.parse({id:`ord_${Date.now()}`,accountId:"acc_01",...input,requestedPrice:p,filledPrice:input.type==="market"?p*(input.side==="buy"?1+slip:1-slip):null,slippage:input.type==="market"?.08:null,status:input.type==="market"?"filled":"pending",source:"manual",rejectionReason:null,createdAt:new Date().toISOString(),filledAt:input.type==="market"?new Date().toISOString():null});orders=[order,...orders];return order}
